# conda environment description file for the Analysis-Aline environment
#
# Create a conda environment in which to run Jupyter Notebooks in this directory with:
#
#   $ conda env create -f environment.yaml
#   $ conda activate Analysis-Aline
#
# To add new packages to the environment,
# add them to the dependencies list below,
# then update the activated environment with:
#
#   (Analysis-Aline)$ conda env update -f environment.yaml

name: Analysis-Aline

channels:
  - conda-forge
  - defaults

dependencies:
  - arrow
  - bottleneck
  - cliff
  - cmocean
  - coverage
  - dask
  - f90nml
  - gsw
  - ipdb
  - ipython
  - jupyterlab
  - lxml
  - matplotlib
  - nbsphinx
  - netCDF4
  - numpy
  - pandas
  - pip
  - progressbar
  - pytest
  - python=3
  - pytz
  - python-dateutil
  - pyyaml
  - requests
  - retrying
  - scipy
  - sphinx
  - sphinx_rtd_theme
  - xarray
  - zeep
  - pip:
    - angles
